### ISSUE TITLE
Dump output is obviously wrong

### ISSUE THREAD

**Issue by sarsanaee** [sarsanaee/Chronometer#7]
Hello,

Dump doesn't seem to be correct because we cannot have this large number is the L4. I can guess what is happening.

We need to see if we have counted a page table entry from any level, we shouldn't count that again.

Thanks

**Comment by fshahinfar1** [comment]
Since commit `1db1cdd30f`, we check not to follow a path which we have visited before. This should prevent some issues, but, still the out put dump from a test ran on the server is obviously wrong!

I guess it can be caused by an other issue. The kernel module, currently, takes snapshots from the state of  the page table structure. It means that the out put available at `/dev/ptdump` is changing priodically, and, the new dump reflects the current state of the page table irrespective to the previous states.

I think we should have a **time series** dump of the page table to be able to decide what is really happening during a test. 

(I think it is best to leave this issue opened for now until we can approve the out put dump is correct)

**Comment by fshahinfar1** [comment]
A possible cause can be, if we follow a pgd entry we add it to the set and the next time, that entry is skiped. Even if more entries have been added in lower levels (pmd, pud, pte)

**Comment by sarsanaee** [comment]
How about his: If we are dumping three snapshots, better to see three dumps in `/dev/ptdump`, rather than just one. Then you can following the diff between each dump! THAT MIGHT HELP.
